package rules.Assignment.GlobalActivityAssignmentRules_dir

@gw.rules.RuleName("Activity based on pattern")
internal class Activitybasedonpattern {
  static function doCondition(activity : entity.Activity) : boolean {
    
/*start00rule*/
return activity.ActivityPattern <> null
/*end00rule*/

  }

  static function doAction(activity : entity.Activity, actions : gw.rules.Action) {

/*start00rule*/
/* Use child rules to assign based on pattern type */
/*end00rule*/

  }
}
