package rules.Assignment.GlobalPreRenewalAssignmentRules_dir

@gw.rules.RuleName("Customer Service Representative")
internal class CustomerServiceRepresentative {
  static function doCondition(policy : entity.Policy) : boolean {
    
/*start00rule*/
return policy.CurrentRoleAssignment.Role == "CustomerRep"
/*end00rule*/

  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {

/*start00rule*/

/*end00rule*/

  }
}
