package rules.Assignment.GlobalPreRenewalAssignmentRules_dir

@gw.rules.RuleName("Underwriter")
internal class Underwriter {
  static function doCondition(policy : entity.Policy) : boolean {
    
/*start00rule*/
return policy.CurrentRoleAssignment.Role == "Underwriter"
/*end00rule*/

  }

  static function doAction(policy : entity.Policy, actions : gw.rules.Action) {

/*start00rule*/

/*end00rule*/

  }
}
