package rules.EventMessage.EventFired_dir.IndexingSystem_dir

@gw.rules.RuleName("Policy Period")
internal class PolicyPeriod {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
    return /*start00rule*/messageContext.Root typeis PolicyPeriod/*end00rule*/
  }

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {
/*start00rule*//*end00rule*/
  }
}
