package rules.Validation.AccountValidationRules_dir.Test_dir

@gw.rules.RuleName("Fail Validation")
internal class FailValidation {
  static function doCondition(account : entity.Account) : boolean {
    
/*start00rule*/
return account.PublicID == "Fail Validation"
/*end00rule*/

  }

  static function doAction(account : entity.Account, actions : gw.rules.Action) {

/*start00rule*/
account.reject( "loadsave", "Test-Fail-Account-Validation", null, null )
/*end00rule*/

  }
}
