<?xml version="1.0"?>
<!-- Generated WSDL for gw.webservice.pc.pc700.contact.AddressAPI web service -->
<wsdl:definitions targetNamespace="http://guidewire.com/pc/ws/gw/webservice/pc/pc700/contact/AddressAPI" name="AddressAPI" xmlns:gwsoap="http://guidewire.com/ws/soapheaders" xmlns:gwwsdl="http://guidewire.com/pl/wsdl" xmlns:pogo="http://guidewire.com/pc/ws/gw/webservice/pc/pc700/contact/AddressData" xmlns:pogo2="http://guidewire.com/pc/typekey" xmlns:soap11="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:tns="http://guidewire.com/pc/ws/gw/webservice/pc/pc700/contact/AddressAPI" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <xs:schema targetNamespace="http://guidewire.com/pc/ws/gw/webservice/pc/pc700/contact/AddressAPI" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:import namespace="http://guidewire.com/ws/soapheaders" schemaLocation="../../../../../../../gw/xsd/guidewire/soapheaders.xsd"/>
      <xs:import namespace="http://guidewire.com/pc/typekey"/>
      <xs:import namespace="http://guidewire.com/pc/ws/gw/webservice/pc/pc700/contact/AddressData"/>
      <!-- updateAddress(AddressData, String) -->
      <xs:element name="updateAddress">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="address" minOccurs="0" type="pogo:AddressData"/>
            <xs:element name="publicId" type="xs:string" minOccurs="0"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="updateAddressResponse">
        <xs:complexType/>
      </xs:element>
      <xs:element name="SOAPException">
        <xs:complexType/>
      </xs:element>
      <xs:element name="RequiredFieldException">
        <xs:complexType/>
      </xs:element>
      <xs:element name="BadIdentifierException">
        <xs:complexType/>
      </xs:element>
      <xs:element name="WsiAuthenticationException">
        <xs:complexType/>
      </xs:element>
      <!-- updateAddressOnly(AddressData, String) -->
      <xs:element name="updateAddressOnly">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="address" minOccurs="0" type="pogo:AddressData"/>
            <xs:element name="publicId" type="xs:string" minOccurs="0"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="updateAddressOnlyResponse">
        <xs:complexType/>
      </xs:element>
      <!-- updateAddressAndLinkedAddresses(AddressData, String) -->
      <xs:element name="updateAddressAndLinkedAddresses">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="address" minOccurs="0" type="pogo:AddressData"/>
            <xs:element name="publicId" type="xs:string" minOccurs="0"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="updateAddressAndLinkedAddressesResponse">
        <xs:complexType/>
      </xs:element>
      <!-- updateAddressAndUnlink(AddressData, String) -->
      <xs:element name="updateAddressAndUnlink">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="address" minOccurs="0" type="pogo:AddressData"/>
            <xs:element name="publicId" type="xs:string" minOccurs="0"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="updateAddressAndUnlinkResponse">
        <xs:complexType/>
      </xs:element>
    </xs:schema>
    <xs:schema targetNamespace="http://guidewire.com/pc/ws/gw/webservice/pc/pc700/contact/AddressData" elementFormDefault="qualified" xmlns:gw="http://guidewire.com/xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:import namespace="http://guidewire.com/pc/typekey"/>
      <xs:complexType name="AddressData" gw:deprecated="As of 8.0 use gw.webservice.pc.pc800.contact.AddressData instead">
        <xs:sequence>
          <xs:element name="AddressLine1" type="xs:string" minOccurs="0"/>
          <xs:element name="AddressLine2" type="xs:string" minOccurs="0"/>
          <xs:element name="AddressLine3" type="xs:string" minOccurs="0"/>
          <xs:element name="AddressType" minOccurs="0" type="pogo2:AddressType"/>
          <xs:element name="City" type="xs:string" minOccurs="0"/>
          <xs:element name="Country" minOccurs="0" type="pogo2:Country"/>
          <xs:element name="County" type="xs:string" minOccurs="0"/>
          <xs:element name="Description" type="xs:string" minOccurs="0"/>
          <xs:element name="PostalCode" type="xs:string" minOccurs="0"/>
          <xs:element name="State" minOccurs="0" type="pogo2:State"/>
          <xs:element name="ValidUntil" type="xs:dateTime" gw:type="java.util.Date" minOccurs="0"/>
        </xs:sequence>
      </xs:complexType>
    </xs:schema>
    <xs:schema targetNamespace="http://guidewire.com/pc/typekey" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:import namespace="http://guidewire.com/pc/ws/gw/webservice/pc/pc700/contact/AddressData"/>
      <xs:simpleType name="AddressType">
        <xs:restriction base="xs:string">
          <xs:enumeration value="billing"/>
          <xs:enumeration value="business"/>
          <xs:enumeration value="home"/>
          <xs:enumeration value="other"/>
        </xs:restriction>
      </xs:simpleType>
      <xs:simpleType name="Country">
        <xs:restriction base="xs:string">
          <xs:enumeration value="US"/>
          <xs:enumeration value="CA"/>
          <xs:enumeration value="AF"/>
          <xs:enumeration value="AL"/>
          <xs:enumeration value="DZ"/>
          <xs:enumeration value="AS"/>
          <xs:enumeration value="AD"/>
          <xs:enumeration value="AO"/>
          <xs:enumeration value="AI"/>
          <xs:enumeration value="AQ"/>
          <xs:enumeration value="AG"/>
          <xs:enumeration value="AR"/>
          <xs:enumeration value="AM"/>
          <xs:enumeration value="AW"/>
          <xs:enumeration value="AU"/>
          <xs:enumeration value="AT"/>
          <xs:enumeration value="AZ"/>
          <xs:enumeration value="BS"/>
          <xs:enumeration value="BH"/>
          <xs:enumeration value="BD"/>
          <xs:enumeration value="BB"/>
          <xs:enumeration value="BY"/>
          <xs:enumeration value="BE"/>
          <xs:enumeration value="BZ"/>
          <xs:enumeration value="BJ"/>
          <xs:enumeration value="BM"/>
          <xs:enumeration value="BT"/>
          <xs:enumeration value="BO"/>
          <xs:enumeration value="BA"/>
          <xs:enumeration value="BW"/>
          <xs:enumeration value="BV"/>
          <xs:enumeration value="BR"/>
          <xs:enumeration value="IO"/>
          <xs:enumeration value="VG"/>
          <xs:enumeration value="BN"/>
          <xs:enumeration value="BG"/>
          <xs:enumeration value="BF"/>
          <xs:enumeration value="BI"/>
          <xs:enumeration value="KH"/>
          <xs:enumeration value="CM"/>
          <xs:enumeration value="CV"/>
          <xs:enumeration value="KY"/>
          <xs:enumeration value="CF"/>
          <xs:enumeration value="TD"/>
          <xs:enumeration value="CL"/>
          <xs:enumeration value="CN"/>
          <xs:enumeration value="CX"/>
          <xs:enumeration value="CC"/>
          <xs:enumeration value="CO"/>
          <xs:enumeration value="KM"/>
          <xs:enumeration value="CG"/>
          <xs:enumeration value="CD"/>
          <xs:enumeration value="CK"/>
          <xs:enumeration value="CR"/>
          <xs:enumeration value="HR"/>
          <xs:enumeration value="CU"/>
          <xs:enumeration value="CY"/>
          <xs:enumeration value="CZ"/>
          <xs:enumeration value="DK"/>
          <xs:enumeration value="DJ"/>
          <xs:enumeration value="DM"/>
          <xs:enumeration value="DO"/>
          <xs:enumeration value="EC"/>
          <xs:enumeration value="EG"/>
          <xs:enumeration value="SV"/>
          <xs:enumeration value="GQ"/>
          <xs:enumeration value="ER"/>
          <xs:enumeration value="EE"/>
          <xs:enumeration value="ET"/>
          <xs:enumeration value="FK"/>
          <xs:enumeration value="FO"/>
          <xs:enumeration value="FJ"/>
          <xs:enumeration value="FI"/>
          <xs:enumeration value="FR"/>
          <xs:enumeration value="GF"/>
          <xs:enumeration value="PF"/>
          <xs:enumeration value="TF"/>
          <xs:enumeration value="GA"/>
          <xs:enumeration value="GM"/>
          <xs:enumeration value="GE"/>
          <xs:enumeration value="DE"/>
          <xs:enumeration value="GH"/>
          <xs:enumeration value="GI"/>
          <xs:enumeration value="GR"/>
          <xs:enumeration value="GL"/>
          <xs:enumeration value="GD"/>
          <xs:enumeration value="GP"/>
          <xs:enumeration value="GU"/>
          <xs:enumeration value="GT"/>
          <xs:enumeration value="GN"/>
          <xs:enumeration value="GW"/>
          <xs:enumeration value="GY"/>
          <xs:enumeration value="HT"/>
          <xs:enumeration value="HM"/>
          <xs:enumeration value="HN"/>
          <xs:enumeration value="HK"/>
          <xs:enumeration value="HU"/>
          <xs:enumeration value="IS"/>
          <xs:enumeration value="IN"/>
          <xs:enumeration value="ID"/>
          <xs:enumeration value="IR"/>
          <xs:enumeration value="IQ"/>
          <xs:enumeration value="IE"/>
          <xs:enumeration value="IL"/>
          <xs:enumeration value="IT"/>
          <xs:enumeration value="CI"/>
          <xs:enumeration value="JM"/>
          <xs:enumeration value="JP"/>
          <xs:enumeration value="JO"/>
          <xs:enumeration value="KZ"/>
          <xs:enumeration value="KE"/>
          <xs:enumeration value="KI"/>
          <xs:enumeration value="KP"/>
          <xs:enumeration value="KR"/>
          <xs:enumeration value="KW"/>
          <xs:enumeration value="KG"/>
          <xs:enumeration value="LA"/>
          <xs:enumeration value="LV"/>
          <xs:enumeration value="LB"/>
          <xs:enumeration value="LS"/>
          <xs:enumeration value="LR"/>
          <xs:enumeration value="LY"/>
          <xs:enumeration value="LI"/>
          <xs:enumeration value="LT"/>
          <xs:enumeration value="LU"/>
          <xs:enumeration value="MO"/>
          <xs:enumeration value="MK"/>
          <xs:enumeration value="MG"/>
          <xs:enumeration value="MW"/>
          <xs:enumeration value="MY"/>
          <xs:enumeration value="MV"/>
          <xs:enumeration value="ML"/>
          <xs:enumeration value="MT"/>
          <xs:enumeration value="MH"/>
          <xs:enumeration value="MQ"/>
          <xs:enumeration value="MR"/>
          <xs:enumeration value="MU"/>
          <xs:enumeration value="YT"/>
          <xs:enumeration value="MX"/>
          <xs:enumeration value="FM"/>
          <xs:enumeration value="MD"/>
          <xs:enumeration value="MC"/>
          <xs:enumeration value="MN"/>
          <xs:enumeration value="ME"/>
          <xs:enumeration value="MS"/>
          <xs:enumeration value="MA"/>
          <xs:enumeration value="MZ"/>
          <xs:enumeration value="MM"/>
          <xs:enumeration value="NA"/>
          <xs:enumeration value="NR"/>
          <xs:enumeration value="NP"/>
          <xs:enumeration value="NL"/>
          <xs:enumeration value="AN"/>
          <xs:enumeration value="NC"/>
          <xs:enumeration value="NZ"/>
          <xs:enumeration value="NI"/>
          <xs:enumeration value="NE"/>
          <xs:enumeration value="NG"/>
          <xs:enumeration value="NU"/>
          <xs:enumeration value="NF"/>
          <xs:enumeration value="MP"/>
          <xs:enumeration value="NO"/>
          <xs:enumeration value="OM"/>
          <xs:enumeration value="PK"/>
          <xs:enumeration value="PW"/>
          <xs:enumeration value="PS"/>
          <xs:enumeration value="PA"/>
          <xs:enumeration value="PG"/>
          <xs:enumeration value="PY"/>
          <xs:enumeration value="PE"/>
          <xs:enumeration value="PH"/>
          <xs:enumeration value="PN"/>
          <xs:enumeration value="PL"/>
          <xs:enumeration value="PT"/>
          <xs:enumeration value="PR"/>
          <xs:enumeration value="QA"/>
          <xs:enumeration value="RE"/>
          <xs:enumeration value="RO"/>
          <xs:enumeration value="RU"/>
          <xs:enumeration value="RW"/>
          <xs:enumeration value="BL"/>
          <xs:enumeration value="MF"/>
          <xs:enumeration value="WS"/>
          <xs:enumeration value="SM"/>
          <xs:enumeration value="ST"/>
          <xs:enumeration value="SA"/>
          <xs:enumeration value="SN"/>
          <xs:enumeration value="RS"/>
          <xs:enumeration value="SC"/>
          <xs:enumeration value="SL"/>
          <xs:enumeration value="SG"/>
          <xs:enumeration value="SK"/>
          <xs:enumeration value="SI"/>
          <xs:enumeration value="SB"/>
          <xs:enumeration value="SO"/>
          <xs:enumeration value="ZA"/>
          <xs:enumeration value="GS"/>
          <xs:enumeration value="ES"/>
          <xs:enumeration value="LK"/>
          <xs:enumeration value="SH"/>
          <xs:enumeration value="KN"/>
          <xs:enumeration value="LC"/>
          <xs:enumeration value="PM"/>
          <xs:enumeration value="VC"/>
          <xs:enumeration value="SD"/>
          <xs:enumeration value="SR"/>
          <xs:enumeration value="SJ"/>
          <xs:enumeration value="SZ"/>
          <xs:enumeration value="SE"/>
          <xs:enumeration value="CH"/>
          <xs:enumeration value="SY"/>
          <xs:enumeration value="TW"/>
          <xs:enumeration value="TJ"/>
          <xs:enumeration value="TZ"/>
          <xs:enumeration value="TH"/>
          <xs:enumeration value="TL"/>
          <xs:enumeration value="TG"/>
          <xs:enumeration value="TK"/>
          <xs:enumeration value="TO"/>
          <xs:enumeration value="TT"/>
          <xs:enumeration value="TN"/>
          <xs:enumeration value="TR"/>
          <xs:enumeration value="TM"/>
          <xs:enumeration value="TC"/>
          <xs:enumeration value="TV"/>
          <xs:enumeration value="UM"/>
          <xs:enumeration value="VI"/>
          <xs:enumeration value="UG"/>
          <xs:enumeration value="UA"/>
          <xs:enumeration value="AE"/>
          <xs:enumeration value="GB"/>
          <xs:enumeration value="UY"/>
          <xs:enumeration value="UZ"/>
          <xs:enumeration value="VU"/>
          <xs:enumeration value="VA"/>
          <xs:enumeration value="VE"/>
          <xs:enumeration value="VN"/>
          <xs:enumeration value="WF"/>
          <xs:enumeration value="EH"/>
          <xs:enumeration value="YE"/>
          <xs:enumeration value="ZM"/>
          <xs:enumeration value="ZW"/>
          <xs:enumeration value="unknown"/>
        </xs:restriction>
      </xs:simpleType>
      <xs:simpleType name="State">
        <xs:restriction base="xs:string">
          <xs:enumeration value="Hokkaido"/>
          <xs:enumeration value="Aomori"/>
          <xs:enumeration value="Iwate"/>
          <xs:enumeration value="Miyagi"/>
          <xs:enumeration value="Akita"/>
          <xs:enumeration value="Yamagata"/>
          <xs:enumeration value="Fukushima"/>
          <xs:enumeration value="Ibaraki"/>
          <xs:enumeration value="AU_JBT"/>
          <xs:enumeration value="Tochigi"/>
          <xs:enumeration value="Gumma"/>
          <xs:enumeration value="Saitama"/>
          <xs:enumeration value="Chiba"/>
          <xs:enumeration value="Tokyo"/>
          <xs:enumeration value="Kanagawa"/>
          <xs:enumeration value="Niigata"/>
          <xs:enumeration value="Toyama"/>
          <xs:enumeration value="Ishikawa"/>
          <xs:enumeration value="Fukui"/>
          <xs:enumeration value="Yamanashi"/>
          <xs:enumeration value="Nagano"/>
          <xs:enumeration value="Gifu"/>
          <xs:enumeration value="Shizuoka"/>
          <xs:enumeration value="Aichi"/>
          <xs:enumeration value="Mie"/>
          <xs:enumeration value="Shiga"/>
          <xs:enumeration value="Kyoto"/>
          <xs:enumeration value="Osaka"/>
          <xs:enumeration value="Hyogo"/>
          <xs:enumeration value="Nara"/>
          <xs:enumeration value="Wakayama"/>
          <xs:enumeration value="Tottori"/>
          <xs:enumeration value="Shimane"/>
          <xs:enumeration value="Okayama"/>
          <xs:enumeration value="Hiroshima"/>
          <xs:enumeration value="Yamaguchi"/>
          <xs:enumeration value="Tokushima"/>
          <xs:enumeration value="Kagawa"/>
          <xs:enumeration value="Ehime"/>
          <xs:enumeration value="Kochi"/>
          <xs:enumeration value="Fukuoka"/>
          <xs:enumeration value="Saga"/>
          <xs:enumeration value="Nagasaki"/>
          <xs:enumeration value="Kumamoto"/>
          <xs:enumeration value="Oita"/>
          <xs:enumeration value="Miyazaki"/>
          <xs:enumeration value="Kagoshima"/>
          <xs:enumeration value="Okinawa"/>
          <xs:enumeration value="AU_ACT"/>
          <xs:enumeration value="AL"/>
          <xs:enumeration value="AK"/>
          <xs:enumeration value="AB"/>
          <xs:enumeration value="AZ"/>
          <xs:enumeration value="AR"/>
          <xs:enumeration value="DE_BW"/>
          <xs:enumeration value="DE_BY"/>
          <xs:enumeration value="DE_BE"/>
          <xs:enumeration value="DE_BB"/>
          <xs:enumeration value="DE_HB"/>
          <xs:enumeration value="BC"/>
          <xs:enumeration value="CA"/>
          <xs:enumeration value="CO"/>
          <xs:enumeration value="CT"/>
          <xs:enumeration value="DE"/>
          <xs:enumeration value="DC"/>
          <xs:enumeration value="FM"/>
          <xs:enumeration value="FL"/>
          <xs:enumeration value="GA"/>
          <xs:enumeration value="GU"/>
          <xs:enumeration value="DE_HH"/>
          <xs:enumeration value="HI"/>
          <xs:enumeration value="DE_HE"/>
          <xs:enumeration value="ID"/>
          <xs:enumeration value="IL"/>
          <xs:enumeration value="IN"/>
          <xs:enumeration value="IA"/>
          <xs:enumeration value="KS"/>
          <xs:enumeration value="KY"/>
          <xs:enumeration value="LA"/>
          <xs:enumeration value="DE_NI"/>
          <xs:enumeration value="ME"/>
          <xs:enumeration value="MB"/>
          <xs:enumeration value="MH"/>
          <xs:enumeration value="MD"/>
          <xs:enumeration value="MA"/>
          <xs:enumeration value="DE_MV"/>
          <xs:enumeration value="MI"/>
          <xs:enumeration value="MN"/>
          <xs:enumeration value="MS"/>
          <xs:enumeration value="MO"/>
          <xs:enumeration value="MT"/>
          <xs:enumeration value="NE"/>
          <xs:enumeration value="NV"/>
          <xs:enumeration value="NB"/>
          <xs:enumeration value="NH"/>
          <xs:enumeration value="NJ"/>
          <xs:enumeration value="NM"/>
          <xs:enumeration value="AU_NSW"/>
          <xs:enumeration value="NY"/>
          <xs:enumeration value="NL"/>
          <xs:enumeration value="NC"/>
          <xs:enumeration value="ND"/>
          <xs:enumeration value="DE_NW"/>
          <xs:enumeration value="MP"/>
          <xs:enumeration value="AU_NT"/>
          <xs:enumeration value="NT"/>
          <xs:enumeration value="NS"/>
          <xs:enumeration value="NU"/>
          <xs:enumeration value="OH"/>
          <xs:enumeration value="OK"/>
          <xs:enumeration value="ON"/>
          <xs:enumeration value="OR"/>
          <xs:enumeration value="PA"/>
          <xs:enumeration value="PE"/>
          <xs:enumeration value="PR"/>
          <xs:enumeration value="QC"/>
          <xs:enumeration value="AU_QLD"/>
          <xs:enumeration value="DE_RP"/>
          <xs:enumeration value="RI"/>
          <xs:enumeration value="DE_SL"/>
          <xs:enumeration value="SK"/>
          <xs:enumeration value="DE_SN"/>
          <xs:enumeration value="DE_ST"/>
          <xs:enumeration value="DE_SH"/>
          <xs:enumeration value="AU_SA"/>
          <xs:enumeration value="SC"/>
          <xs:enumeration value="SD"/>
          <xs:enumeration value="AU_TAS"/>
          <xs:enumeration value="TN"/>
          <xs:enumeration value="TX"/>
          <xs:enumeration value="DE_TH"/>
          <xs:enumeration value="UT"/>
          <xs:enumeration value="VT"/>
          <xs:enumeration value="AU_VIC"/>
          <xs:enumeration value="VI"/>
          <xs:enumeration value="VA"/>
          <xs:enumeration value="WA"/>
          <xs:enumeration value="WV"/>
          <xs:enumeration value="AU_WA"/>
          <xs:enumeration value="WI"/>
          <xs:enumeration value="WY"/>
          <xs:enumeration value="YT"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:schema>
  </wsdl:types>
  <wsdl:portType name="AddressAPIPortType">
    <wsdl:operation name="updateAddress">
      <wsdl:documentation>@deprecated: As of 8.0 use gw.webservice.pc.pc800.contact.AddressAPI instead</wsdl:documentation>
      <wsdl:input name="updateAddress" message="tns:updateAddress"/>
      <wsdl:output name="updateAddressResponse" message="tns:updateAddressResponse"/>
      <!-- If communication errors occur -->
      <wsdl:fault name="SOAPException" message="tns:SOAPException"/>
      <!-- If required field is missing -->
      <wsdl:fault name="RequiredFieldException" message="tns:RequiredFieldException"/>
      <!-- If cannot find entity with given identifier -->
      <wsdl:fault name="BadIdentifierException" message="tns:BadIdentifierException"/>
      <wsdl:fault name="WsiAuthenticationException" message="tns:WsiAuthenticationException"/>
    </wsdl:operation>
    <wsdl:operation name="updateAddressOnly">
      <wsdl:documentation>@deprecated: As of 8.0 use gw.webservice.pc.pc800.contact.AddressAPI instead</wsdl:documentation>
      <wsdl:input name="updateAddressOnly" message="tns:updateAddressOnly"/>
      <wsdl:output name="updateAddressOnlyResponse" message="tns:updateAddressOnlyResponse"/>
      <!-- If communication errors occur -->
      <wsdl:fault name="SOAPException" message="tns:SOAPException"/>
      <!-- If required field is missing -->
      <wsdl:fault name="RequiredFieldException" message="tns:RequiredFieldException"/>
      <!-- If cannot find entity with given identifier -->
      <wsdl:fault name="BadIdentifierException" message="tns:BadIdentifierException"/>
      <wsdl:fault name="WsiAuthenticationException" message="tns:WsiAuthenticationException"/>
    </wsdl:operation>
    <wsdl:operation name="updateAddressAndLinkedAddresses">
      <wsdl:documentation>@deprecated: As of 8.0 use gw.webservice.pc.pc800.contact.AddressAPI instead</wsdl:documentation>
      <wsdl:input name="updateAddressAndLinkedAddresses" message="tns:updateAddressAndLinkedAddresses"/>
      <wsdl:output name="updateAddressAndLinkedAddressesResponse" message="tns:updateAddressAndLinkedAddressesResponse"/>
      <!-- If communication errors occur -->
      <wsdl:fault name="SOAPException" message="tns:SOAPException"/>
      <!-- If required field is missing -->
      <wsdl:fault name="RequiredFieldException" message="tns:RequiredFieldException"/>
      <!-- If cannot find entity with given identifier -->
      <wsdl:fault name="BadIdentifierException" message="tns:BadIdentifierException"/>
      <wsdl:fault name="WsiAuthenticationException" message="tns:WsiAuthenticationException"/>
    </wsdl:operation>
    <wsdl:operation name="updateAddressAndUnlink">
      <wsdl:documentation>@deprecated: As of 8.0 use gw.webservice.pc.pc800.contact.AddressAPI instead</wsdl:documentation>
      <wsdl:input name="updateAddressAndUnlink" message="tns:updateAddressAndUnlink"/>
      <wsdl:output name="updateAddressAndUnlinkResponse" message="tns:updateAddressAndUnlinkResponse"/>
      <!-- If communication errors occur -->
      <wsdl:fault name="SOAPException" message="tns:SOAPException"/>
      <!-- If required field is missing -->
      <wsdl:fault name="RequiredFieldException" message="tns:RequiredFieldException"/>
      <!-- If cannot find entity with given identifier -->
      <wsdl:fault name="BadIdentifierException" message="tns:BadIdentifierException"/>
      <wsdl:fault name="WsiAuthenticationException" message="tns:WsiAuthenticationException"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="AddressAPISoap12Binding" type="tns:AddressAPIPortType">
    <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <wsdl:operation name="updateAddress">
      <soap12:operation soapActionRequired="false" style="document"/>
      <wsdl:input name="updateAddress">
        <soap12:body use="literal"/>
        <soap12:header message="tns:gw-authentication" part="gw-authentication" use="literal"/>
        <soap12:header message="tns:gw-locale" part="gw-locale" use="literal"/>
      </wsdl:input>
      <wsdl:output name="updateAddressResponse">
        <soap12:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="SOAPException">
        <soap12:fault name="SOAPException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="RequiredFieldException">
        <soap12:fault name="RequiredFieldException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="BadIdentifierException">
        <soap12:fault name="BadIdentifierException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="WsiAuthenticationException">
        <soap12:fault name="WsiAuthenticationException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="updateAddressOnly">
      <soap12:operation soapActionRequired="false" style="document"/>
      <wsdl:input name="updateAddressOnly">
        <soap12:body use="literal"/>
        <soap12:header message="tns:gw-authentication" part="gw-authentication" use="literal"/>
        <soap12:header message="tns:gw-locale" part="gw-locale" use="literal"/>
      </wsdl:input>
      <wsdl:output name="updateAddressOnlyResponse">
        <soap12:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="SOAPException">
        <soap12:fault name="SOAPException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="RequiredFieldException">
        <soap12:fault name="RequiredFieldException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="BadIdentifierException">
        <soap12:fault name="BadIdentifierException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="WsiAuthenticationException">
        <soap12:fault name="WsiAuthenticationException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="updateAddressAndLinkedAddresses">
      <soap12:operation soapActionRequired="false" style="document"/>
      <wsdl:input name="updateAddressAndLinkedAddresses">
        <soap12:body use="literal"/>
        <soap12:header message="tns:gw-authentication" part="gw-authentication" use="literal"/>
        <soap12:header message="tns:gw-locale" part="gw-locale" use="literal"/>
      </wsdl:input>
      <wsdl:output name="updateAddressAndLinkedAddressesResponse">
        <soap12:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="SOAPException">
        <soap12:fault name="SOAPException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="RequiredFieldException">
        <soap12:fault name="RequiredFieldException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="BadIdentifierException">
        <soap12:fault name="BadIdentifierException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="WsiAuthenticationException">
        <soap12:fault name="WsiAuthenticationException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="updateAddressAndUnlink">
      <soap12:operation soapActionRequired="false" style="document"/>
      <wsdl:input name="updateAddressAndUnlink">
        <soap12:body use="literal"/>
        <soap12:header message="tns:gw-authentication" part="gw-authentication" use="literal"/>
        <soap12:header message="tns:gw-locale" part="gw-locale" use="literal"/>
      </wsdl:input>
      <wsdl:output name="updateAddressAndUnlinkResponse">
        <soap12:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="SOAPException">
        <soap12:fault name="SOAPException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="RequiredFieldException">
        <soap12:fault name="RequiredFieldException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="BadIdentifierException">
        <soap12:fault name="BadIdentifierException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="WsiAuthenticationException">
        <soap12:fault name="WsiAuthenticationException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:binding name="AddressAPISoap11Binding" type="tns:AddressAPIPortType">
    <soap11:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <wsdl:operation name="updateAddress">
      <soap11:operation style="document"/>
      <wsdl:input name="updateAddress">
        <soap11:body use="literal"/>
        <soap11:header message="tns:gw-authentication" part="gw-authentication" use="literal"/>
        <soap11:header message="tns:gw-locale" part="gw-locale" use="literal"/>
      </wsdl:input>
      <wsdl:output name="updateAddressResponse">
        <soap11:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="SOAPException">
        <soap11:fault name="SOAPException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="RequiredFieldException">
        <soap11:fault name="RequiredFieldException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="BadIdentifierException">
        <soap11:fault name="BadIdentifierException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="WsiAuthenticationException">
        <soap11:fault name="WsiAuthenticationException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="updateAddressOnly">
      <soap11:operation style="document"/>
      <wsdl:input name="updateAddressOnly">
        <soap11:body use="literal"/>
        <soap11:header message="tns:gw-authentication" part="gw-authentication" use="literal"/>
        <soap11:header message="tns:gw-locale" part="gw-locale" use="literal"/>
      </wsdl:input>
      <wsdl:output name="updateAddressOnlyResponse">
        <soap11:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="SOAPException">
        <soap11:fault name="SOAPException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="RequiredFieldException">
        <soap11:fault name="RequiredFieldException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="BadIdentifierException">
        <soap11:fault name="BadIdentifierException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="WsiAuthenticationException">
        <soap11:fault name="WsiAuthenticationException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="updateAddressAndLinkedAddresses">
      <soap11:operation style="document"/>
      <wsdl:input name="updateAddressAndLinkedAddresses">
        <soap11:body use="literal"/>
        <soap11:header message="tns:gw-authentication" part="gw-authentication" use="literal"/>
        <soap11:header message="tns:gw-locale" part="gw-locale" use="literal"/>
      </wsdl:input>
      <wsdl:output name="updateAddressAndLinkedAddressesResponse">
        <soap11:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="SOAPException">
        <soap11:fault name="SOAPException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="RequiredFieldException">
        <soap11:fault name="RequiredFieldException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="BadIdentifierException">
        <soap11:fault name="BadIdentifierException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="WsiAuthenticationException">
        <soap11:fault name="WsiAuthenticationException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="updateAddressAndUnlink">
      <soap11:operation style="document"/>
      <wsdl:input name="updateAddressAndUnlink">
        <soap11:body use="literal"/>
        <soap11:header message="tns:gw-authentication" part="gw-authentication" use="literal"/>
        <soap11:header message="tns:gw-locale" part="gw-locale" use="literal"/>
      </wsdl:input>
      <wsdl:output name="updateAddressAndUnlinkResponse">
        <soap11:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="SOAPException">
        <soap11:fault name="SOAPException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="RequiredFieldException">
        <soap11:fault name="RequiredFieldException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="BadIdentifierException">
        <soap11:fault name="BadIdentifierException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="WsiAuthenticationException">
        <soap11:fault name="WsiAuthenticationException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="AddressAPI">
    <wsdl:port name="AddressAPISoap12Port" binding="tns:AddressAPISoap12Binding">
      <soap12:address location="local:///gw/webservice/pc/pc700/contact/AddressAPI"/>
    </wsdl:port>
    <wsdl:port name="AddressAPISoap11Port" binding="tns:AddressAPISoap11Binding">
      <soap11:address location="local:///gw/webservice/pc/pc700/contact/AddressAPI/soap11"/>
    </wsdl:port>
  </wsdl:service>
  <wsdl:message name="updateAddress">
    <wsdl:part name="parameters" element="tns:updateAddress"/>
  </wsdl:message>
  <wsdl:message name="updateAddressResponse">
    <wsdl:part name="parameters" element="tns:updateAddressResponse"/>
  </wsdl:message>
  <wsdl:message name="SOAPException">
    <wsdl:part name="SOAPException" element="tns:SOAPException"/>
  </wsdl:message>
  <wsdl:message name="RequiredFieldException">
    <wsdl:part name="RequiredFieldException" element="tns:RequiredFieldException"/>
  </wsdl:message>
  <wsdl:message name="BadIdentifierException">
    <wsdl:part name="BadIdentifierException" element="tns:BadIdentifierException"/>
  </wsdl:message>
  <wsdl:message name="WsiAuthenticationException">
    <wsdl:part name="WsiAuthenticationException" element="tns:WsiAuthenticationException"/>
  </wsdl:message>
  <wsdl:message name="updateAddressOnly">
    <wsdl:part name="parameters" element="tns:updateAddressOnly"/>
  </wsdl:message>
  <wsdl:message name="updateAddressOnlyResponse">
    <wsdl:part name="parameters" element="tns:updateAddressOnlyResponse"/>
  </wsdl:message>
  <wsdl:message name="updateAddressAndLinkedAddresses">
    <wsdl:part name="parameters" element="tns:updateAddressAndLinkedAddresses"/>
  </wsdl:message>
  <wsdl:message name="updateAddressAndLinkedAddressesResponse">
    <wsdl:part name="parameters" element="tns:updateAddressAndLinkedAddressesResponse"/>
  </wsdl:message>
  <wsdl:message name="updateAddressAndUnlink">
    <wsdl:part name="parameters" element="tns:updateAddressAndUnlink"/>
  </wsdl:message>
  <wsdl:message name="updateAddressAndUnlinkResponse">
    <wsdl:part name="parameters" element="tns:updateAddressAndUnlinkResponse"/>
  </wsdl:message>
  <wsdl:message name="gw-authentication">
    <wsdl:part name="gw-authentication" element="gwsoap:authentication"/>
  </wsdl:message>
  <wsdl:message name="gw-locale">
    <wsdl:part name="gw-locale" element="gwsoap:locale"/>
  </wsdl:message>
</wsdl:definitions>