package rules.EventMessage.EventFired_dir.BillingSystem_dir

@gw.rules.RuleName("Producer")
internal class Organization {
  static function doCondition(messageContext : entity.MessageContext) : boolean {
    
/*start00rule*/
return messageContext.Root typeis Organization
and messageContext.Root.Producer
/*end00rule*/

  }

  static function doAction(messageContext : entity.MessageContext, actions : gw.rules.Action) {

/*start00rule*/

/*end00rule*/

  }
}
