package rules.Renewal.RenewalAutoUpdate_dir

@gw.rules.RuleName("Workers Comp")
internal class WorkersComp {
  static function doCondition(policyPeriod : entity.PolicyPeriod) : boolean {
    
/*start00rule*/
return policyPeriod.Policy.Product == "WorkersComp"
/*end00rule*/

  }

  static function doAction(policyPeriod : entity.PolicyPeriod, actions : gw.rules.Action) {

/*start00rule*/

/*end00rule*/

  }
}
