Ext.define("Titanium.Component",{override:"Ext.Component",initComponent:function(){this.callParent();this.dock&&void 0===this.border&&(this.border=!1)},initStyles:function(){var b=this.border;this.dock&&(this.border=null);this.callParent(arguments);this.border=b}});
Ext.define("Titanium.panel.Panel",{override:"Ext.panel.Panel",initComponent:function(){"inline-details"===this.ui&&!Ext.isDefined(this.initialConfig.bodyPadding)&&(this.bodyPadding=10);this.callParent(arguments)},onAdd:function(b){this.callParent(arguments);b.isXType&&b.isXType("tabpanel")&&b.addCls(Ext.baseCSSPrefix+"list-details-tabpanel")}});
Ext.define("Titanium.layout.component.Dock",{override:"Ext.layout.component.Dock",noBorderClassTable:[0,Ext.baseCSSPrefix+"noborder-l",Ext.baseCSSPrefix+"noborder-b",Ext.baseCSSPrefix+"noborder-bl",Ext.baseCSSPrefix+"noborder-r",Ext.baseCSSPrefix+"noborder-rl",Ext.baseCSSPrefix+"noborder-rb",Ext.baseCSSPrefix+"noborder-rbl",Ext.baseCSSPrefix+"noborder-t",Ext.baseCSSPrefix+"noborder-tl",Ext.baseCSSPrefix+"noborder-tb",Ext.baseCSSPrefix+"noborder-tbl",Ext.baseCSSPrefix+"noborder-tr",Ext.baseCSSPrefix+
"noborder-trl",Ext.baseCSSPrefix+"noborder-trb",Ext.baseCSSPrefix+"noborder-trbl"],edgeMasks:{top:8,right:4,bottom:2,left:1},handleItemBorders:function(){var b=0,h=this.owner,l=h.bodyBorder,k=h.border,c=this.collapsed,t=this.edgeMasks,m=this.noBorderClassTable,p=h.dockedItems.generation,a,q,r,s,e,n,d,f,g;if(this.initializedBorders!==p){f=[];g=[];q=this.getBorderCollapseTable();m=this.getBorderClassTable?this.getBorderClassTable():m;this.initializedBorders=p;this.collapsed=!1;p=this.getDockedItems();
this.collapsed=c;r=0;for(s=p.length;r<s;r++)if(e=p[r],!e.ignoreBorderManagement){n=e.dock;d=c=0;f.length=0;g.length=0;"bottom"!==n&&(b&8?a=e.border:(a=k,!1!==a&&(c+=8)),!1===a&&(d+=8));"left"!==n&&(b&4?a=e.border:(a=k,!1!==a&&(c+=4)),!1===a&&(d+=4));"top"!==n&&(b&2?a=e.border:(a=k,!1!==a&&(c+=2)),!1===a&&(d+=2));"right"!==n&&(b&1?a=e.border:(a=k,!1!==a&&(c+=1)),!1===a&&(d+=1));if((a=e.lastBorderMask)!==d)e.lastBorderMask=d,a&&(g[0]=m[a]),d&&(f[0]=m[d]);if((a=e.lastBorderCollapse)!==c)e.lastBorderCollapse=
c,a&&(g[g.length]=q[a]),c&&(f[f.length]=q[c]);g.length&&e.removeCls(g);f.length&&e.addCls(f);b|=t[n]}d=c=0;f.length=0;g.length=0;b&8?a=l:(a=k,!1!==a&&(c+=8));!1===a&&(d+=8);b&4?a=l:(a=k,!1!==a&&(c+=4));!1===a&&(d+=4);b&2?a=l:(a=k,!1!==a&&(c+=2));!1===a&&(d+=2);b&1?a=l:(a=k,!1!==a&&(c+=1));!1===a&&(d+=1);if((a=this.lastBodyBorderMask)!==d)this.lastBodyBorderMask=d,a&&(g[0]=m[a]),d&&(f[0]=m[d]);if((a=this.lastBodyBorderCollapse)!==c)this.lastBodyBorderCollapse=c,a&&(g[g.length]=q[a]),c&&(f[f.length]=
q[c]);g.length&&h.removeBodyCls(g);f.length&&h.addBodyCls(f)}},onRemove:function(b){var h=b.lastBorderMask;!b.isDestroyed&&(!b.ignoreBorderManagement&&h)&&(b.lastBorderMask=0,b.removeCls(this.noBorderClassTable[h]));this.callParent([b])}});Ext.define("Titanium.toolbar.Toolbar",{override:"Ext.toolbar.Toolbar",usePlainButtons:!1,border:!1});Ext.define("Titanium.container.ButtonGroup",{override:"Ext.container.ButtonGroup",usePlainButtons:!1});
Ext.define("Titanium.toolbar.Paging",{override:"Ext.toolbar.Paging",defaultButtonUI:"default-toolbar"});Ext.define("Titanium.picker.Month",{override:"Ext.picker.Month",measureMaxHeight:36});Ext.define("Titanium.form.field.HtmlEditor",{override:"Ext.form.field.HtmlEditor",defaultButtonUI:"default-toolbar"});Ext.define("Titanium.panel.Table",{override:"Ext.panel.Table",bodyBorder:!0});Ext.define("Titanium.grid.RowEditor",{override:"Ext.grid.RowEditor",buttonUI:"default-toolbar"});
Ext.define("Titanium.resizer.Splitter",{override:"Ext.resizer.Splitter",size:8});Ext.define("Titanium.menu.Menu",{override:"Ext.menu.Menu",showSeparator:!1,border:!1,bodyBorder:!1});Ext.define("Titanium.menu.Separator",{override:"Ext.menu.Separator",border:!0});Ext.define("Titanium.panel.Tool",{override:"Ext.panel.Tool",height:16,width:16});Ext.define("Titanium.tab.Bar",{override:"Ext.tab.Bar",height:30});Ext.define("Titanium.tab.Tab",{override:"Ext.tab.Tab",border:!1,margins:"2 0 0 0"});
Ext.define("Titanium.tree.Column",{override:"Ext.tree.Column",treeRenderer:function(b,h,l){h.tdCls+=" "+(Ext.baseCSSPrefix+"tree-node-depth-"+l.getDepth());return this.callParent(arguments)}});Ext.define("Titanium.tab.Panel",{override:"Ext.tab.Panel",border:!1,bodyBorder:!1,initBorderProps:Ext.emptyFn,initBodyBorder:function(){!0!==this.bodyBorder&&this.callParent()},applyDefaults:function(b){b=this.callParent([b]);Ext.applyIf(b,{border:!1,bodyBorder:!1});return b}});
Ext.define("Titanium.tree.Panel",{override:"Ext.tree.Panel",initComponent:function(){"tree-navigation"===this.ui&&(Ext.isDefined(this.initialConfig.lines)||(this.lines=!1),Ext.isDefined(this.initialConfig.border)||(this.border=!1));this.callParent(arguments)}});